# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=26.1.2
	loader_version=0.19.2
	loom_version=1.16-SNAPSHOT

# Mod Properties
	mod_version = 1.2.0
	maven_group = com.github.nyuppo
	archives_base_name = hotbarcycle

# Dependencies
	fabric_version=0.146.1+26.1.2

# Config
	cloth_config = 26.1.154
	mod_menu = 18.0.0-alpha.8

# Compat
	inventory_profiles_next = 26.1-2.3.1
